# Generated by Django 3.2.6 on 2022-06-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='build_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_area', models.CharField(blank=True, help_text='鄉鎮市區', max_length=20)),
                ('total_number_floors', models.CharField(blank=True, help_text='總樓層數', max_length=20)),
                ('build_type', models.CharField(blank=True, help_text='建物型態', max_length=20)),
                ('build_city', models.CharField(blank=True, help_text='建物城市', max_length=20)),
            ],
            options={
                'db_table': 'build_info',
                'ordering': ['build_city'],
            },
        ),
    ]
